### ISSUE TITLE
Turrets not spawning

### ISSUE THREAD

**Issue by MrSlato** [DreadPirateAU/JEBUS#11] opened 2020-08-16 08:33 UTC
When attempting to spawn a manned turret with JEBUS, it will fail. Tried debugging it and get the following as an example:

`Synchronized trigger activation present`
`Spawning group: O Alpha 1-2`
`O Alpha 1-2 eliminated. Waiting for respawn.`
`Respawn delay = 30 seconds`

Seems that either the unit doesn't spawn at all or is instantly eliminated.
Attached test VR mission.
[JEBUS_Test.VR.zip](https://github.com/DreadPirateAU/JEBUS/files/5080274/JEBUS_Test.VR.zip)

**Comment by DreadPirateAU** [comment] 2020-08-16 11:21
Yeah, I've never been able to get JEBUS to work with static weapons and I don't know what the problem is.

As a workaround, here's what I do:

1. Place the static weapon in the editor
2. Spawn the gunner with JEBUS and give him a "GET IN NEAREST" waypoint near the static weapon
3. Sync a Vehicle Respawn module to the static weapon (if required)

I'm in lockdown at the moment, so I might work on adding support for static weapons to JEBUS.

**Comment by MrSlato** [comment] 2020-08-16 11:37
Hmm. Interesting as I thought turrets were almost the same method as vehicles. Not the end of the world at least.

**Comment by DreadPirateAU** [comment] 2020-08-17 04:07
I think I've found the issue. The saveVehicle  function only works if the vehicle has a driver. Static weapons only have gunners.....

That's an easy fix. Just doing some testing before I push out an update.....

Just to clarify: You're not really interested in respawning the turret over and over again. You mainly want to use the trigger activation and "LIVES=", [1,1] ?

By the way, "LIVES=", 1 works as well......

**Comment by MrSlato** [comment] 2020-08-17 09:08
> Just to clarify: You're not really interested in respawning the turret over and over again. You mainly want to use the trigger activation and "LIVES=", [1,1] ?
Yeah, there are some occations when a turret needs to respawned but 90% of the time its just one.
> By the way, "LIVES=", 1 works as well......
Cheers, didn't know that!

**Comment by DreadPirateAU** [comment] 2020-08-19 05:13
I've updated JEBUS to support static weapons. It places it exactly where it was in the editor, which suits a "LIVES=" 1 scenario, but might cause collision problems with respawning.

Also had reports of groups not spawning intermittently and that should be fixed now.....

**Closed by DreadPirateAU** 2020-08-19 05:13 UTC
